# Generated by Django 6.0.6 on 2026-06-24 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_backinstockrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backinstockrequest',
            name='email',
            field=models.EmailField(help_text='Email address for the notification', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='backinstockrequest',
            name='product',
            field=models.ForeignKey(help_text='The product to be notified about', on_delete=django.db.models.deletion.CASCADE, related_name='back_in_stock_requests', to='api.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Display name for the category', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier (auto-populated from name)', max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(help_text='Your email address so we can reply', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(help_text='How can we help you?', verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(help_text='Your full name', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(help_text='Shipping address including street, city, and postal code', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(help_text='Customer email for order notifications', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gift_card_code',
            field=models.CharField(blank=True, help_text='Optional gift card code to apply discount', max_length=50, verbose_name='gift card code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gift_card_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount amount from gift card (auto-calculated)', max_digits=5, null=True, verbose_name='gift card discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(help_text='Full name for shipping', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Order Placed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='placed', help_text='Current order status in the fulfillment lifecycle', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('upgrade', 'Upgrade'), ('membership', 'Membership')], default='product', help_text='Type of line item: product, upgrade, or membership', max_length=20, verbose_name='item type'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(help_text='Item name shown on the receipt', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='The order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price at time of purchase', max_digits=8, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The product being ordered (optional for custom items)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units ordered', verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Which category this product belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Full product description shown on the detail page', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(help_text='URL to the product image (JPG, PNG, or WebP)', max_length=500, verbose_name='image URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='The product display name', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Current selling price in USD', max_digits=8, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(help_text='Average customer rating (0.0–5.0)', verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier (auto-populated from name)', max_length=100, primary_key=True, serialize=False, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.JSONField(default=list, help_text="Key specifications as key-value pairs, e.g. [{'key': 'Weight', 'value': '1.2kg'}]", verbose_name='specifications'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, help_text='Current inventory count (leave blank for unlimited)', null=True, verbose_name='stock'),
        ),
    ]
