# Generated by Django 6.0.6 on 2026-06-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_backinstockrequest_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], help_text='Subscription tier identifier', max_length=20, unique=True, verbose_name='tier')),
                ('name', models.CharField(help_text='Display name for this subscription tier', max_length=100, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly price in USD', max_digits=8, verbose_name='price')),
                ('description', models.TextField(help_text='Short description of what this tier includes', verbose_name='description')),
                ('features', models.JSONField(default=list, help_text='List of features included in this tier', verbose_name='features')),
                ('duration_days', models.IntegerField(default=30, help_text='Billing cycle length in days', verbose_name='duration days')),
                ('active', models.BooleanField(default=True, help_text='Whether this tier is available for purchase', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['price'],
            },
        ),
    ]
