# Generated by Django 6.0.6 on 2026-06-24 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who placed the order (null for guest)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='backinstockrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notification request was created'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the order was placed'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product was added'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the product was last modified'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the subscription tier was created'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the cart was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the cart was last modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item display name', max_length=200, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Unit price at time of adding', max_digits=8, verbose_name='price')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units', verbose_name='quantity')),
                ('image', models.CharField(blank=True, help_text='Image URL (auto-populated for products)', max_length=500, verbose_name='image URL')),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('upgrade', 'Upgrade'), ('membership', 'Membership')], default='product', help_text='Product, upgrade, or membership', max_length=20, verbose_name='item type')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the item was added')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.cart', verbose_name='cart')),
                ('product', models.ForeignKey(blank=True, help_text='The product (null for custom items like upgrades)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the wishlist was created')),
                ('products', models.ManyToManyField(related_name='wishlists', to='api.product', verbose_name='products')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
            },
        ),
    ]
