# Generated by Django 6.0.6 on 2026-06-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_user_alter_backinstockrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('upgrade', 'Upgrade'), ('membership', 'Membership'), ('addon', 'Add-on')], default='product', help_text='Product, upgrade, or membership', max_length=20, verbose_name='item type'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Product'), ('upgrade', 'Upgrade'), ('membership', 'Membership'), ('addon', 'Add-on')], default='product', help_text='Type of line item: product, upgrade, or membership', max_length=20, verbose_name='item type'),
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, help_text='Carrier tracking number', max_length=100, verbose_name='tracking number')),
                ('carrier', models.CharField(blank=True, help_text='Shipping carrier name (UPS, FedEx, USPS, etc.)', max_length=100, verbose_name='carrier')),
                ('tracking_url', models.URLField(blank=True, help_text="Link to the carrier's tracking page", max_length=500, verbose_name='tracking URL')),
                ('estimated_delivery', models.DateField(blank=True, help_text='Estimated delivery date', null=True, verbose_name='estimated delivery')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Timestamp when the order was marked delivered', null=True, verbose_name='delivered at')),
                ('notes', models.TextField(blank=True, help_text='Internal shipping notes', verbose_name='notes')),
                ('order', models.OneToOneField(help_text='The order being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='api.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Order Tracking',
                'verbose_name_plural': 'Order Tracking Records',
            },
        ),
        migrations.CreateModel(
            name='ProductAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Add-on display name (e.g. 'Cleaning Kit')", max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Short description of what this add-on includes', verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Additional cost in USD', max_digits=8, verbose_name='price')),
                ('image', models.CharField(blank=True, help_text='Optional thumbnail image for the add-on', max_length=500, verbose_name='image URL')),
                ('is_available', models.BooleanField(default=True, help_text='Whether this add-on can be purchased', verbose_name='available')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the add-on was created')),
                ('product', models.ForeignKey(help_text='The product this add-on belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='api.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product Add-on',
                'verbose_name_plural': 'Product Add-ons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrackingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text="Status label (e.g. 'Picked Up', 'In Transit', 'Out for Delivery')", max_length=100, verbose_name='status')),
                ('location', models.CharField(blank=True, help_text='City/state where the event occurred', max_length=200, verbose_name='location')),
                ('note', models.TextField(blank=True, help_text='Details about this tracking event', verbose_name='note')),
                ('timestamp', models.DateTimeField(help_text='When this event occurred', verbose_name='timestamp')),
                ('tracking', models.ForeignKey(help_text='The tracking record this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.ordertracking', verbose_name='tracking')),
            ],
            options={
                'verbose_name': 'Tracking History Entry',
                'verbose_name_plural': 'Tracking History Entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
