# Generated by Django 6.0.6 on 2026-07-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cartitem_item_type_alter_orderitem_item_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_slugs',
            field=models.JSONField(default=list, help_text='List of product slug strings', verbose_name='product slugs'),
        ),
    ]
