# Generated by Django 6.0.6 on 2026-07-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_wishlist_products_wishlist_product_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productaddon',
            name='product',
        ),
        migrations.AddField(
            model_name='productaddon',
            name='product_slug',
            field=models.CharField(blank=True, default='', help_text='The product slug this add-on belongs to', max_length=200, verbose_name='product slug'),
        ),
    ]
