# Generated by Django 6.0.6 on 2026-07-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_productaddon_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backinstockrequest',
            name='product',
        ),
        migrations.AddField(
            model_name='backinstockrequest',
            name='product_name',
            field=models.CharField(blank=True, default='', help_text='Product name (for display)', max_length=200, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='backinstockrequest',
            name='product_slug',
            field=models.CharField(default='', help_text='The product slug to be notified about', max_length=200, verbose_name='product slug'),
        ),
    ]
