# Generated by Django 6.0.6 on 2026-07-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_backinstockrequest_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID for tracking payment', max_length=100, verbose_name='Stripe PaymentIntent ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='pending', help_text='Payment status: pending, paid, failed, refunded', max_length=20, verbose_name='payment status'),
        ),
    ]
