# Generated by Django 6.0.6 on 2026-07-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_payment_intent_id_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
