# Generated by Django 6.0.6 on 2026-06-24 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_newslettersubscription_alter_comment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='A short bio about yourself', verbose_name='bio')),
                ('location', models.CharField(blank=True, help_text='Your location', max_length=100, verbose_name='location')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, verbose_name='phone')),
                ('avatar_url', models.URLField(blank=True, help_text='URL to your avatar image', verbose_name='avatar URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the profile was last updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
