# Generated by Django 6.0.6 on 2026-06-24 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload a file (max 4 per task)', upload_to='task_files/', verbose_name='file')),
                ('name', models.CharField(blank=True, help_text='Optional display name for the file', max_length=255, verbose_name='name')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the file was uploaded')),
                ('task', models.ForeignKey(help_text='The task this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='website.task')),
            ],
            options={
                'verbose_name': 'Task File',
                'verbose_name_plural': 'Task Files',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
