# Generated by Django 6.0.6 on 2026-07-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_userprofile_options_alter_contactmessage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='osimart_customer_id',
            field=models.CharField(blank=True, help_text='Corresponding customer ID on Osimart', max_length=255, verbose_name='Osimart customer ID'),
        ),
    ]
