"""API URL configuration — Auth, Cart, Orders, Products, Tracking, Add-ons, Osimart."""

from django.urls import path

from . import views
from . import views_osimart

app_name = "api"

urlpatterns = [
    path('health/', views.health_check, name='health-check'),
    path('auth/csrf/', views.auth_csrf, name='auth-csrf'),
    path('auth/register/', views.auth_register, name='auth-register'),
    path('auth/guest-login/', views.auth_guest_login, name='auth-guest-login'),
    path('auth/osimart-login/', views.osimart_login, name='auth-osimart-login'),
    path('auth/verify/', views.auth_verify, name='auth-verify'),
    path('auth/resend-otp/', views.auth_resend_otp, name='auth-resend-otp'),
    path('auth/staff-login/', views.auth_staff_login, name='auth-staff-login'),
    path('auth/logout/', views.auth_logout, name='auth-logout'),
    path('auth/osimart-sync/', views.osimart_sync, name='auth-osimart-sync'),
    path('auth/profile/', views.auth_profile, name='auth-profile'),
    path('auth/change-password/', views.change_password, name='auth-change-password'),
    path('auth/reset-password/', views.reset_password, name='auth-reset-password'),
    path('auth/password-reset/', views.auth_password_reset_request, name='auth-password-reset-request'),
    path('auth/password-reset/<uidb64>/<token>/', views.auth_password_reset_confirm, name='auth-password-reset-confirm'),
    path('wishlist/', views.wishlist_get, name='wishlist-get'),
    path('wishlist/toggle/', views.wishlist_toggle, name='wishlist-toggle'),
    path('wishlist/check/<slug:slug>/', views.wishlist_check, name='wishlist-check'),
    path('orders/', views.order_list, name='order-list'),
    path('orders/<int:pk>/', views.order_detail, name='order-detail'),
    path('orders/<int:pk>/tracking/', views.order_tracking, name='order-tracking'),
    path('orders/checkout/', views.order_checkout, name='order-checkout'),
    path('admin/orders/', views.admin_order_list, name='admin-order-list'),
    path('admin/orders/<int:pk>/status/', views.admin_order_update_status, name='admin-order-update-status'),
    path('products/<slug:slug>/addons/', views.product_addons, name='product-addons'),
    path('version/', views.api_version, name='api-version'),
    path('newsletter/subscribe/', views.newsletter_subscribe, name='api-newsletter-subscribe'),
    path('back-in-stock/', views.back_in_stock_subscribe, name='api-back-in-stock'),
    path('payments/config/', views.payment_config, name='payment-config'),
    path('payments/create-intent/', views.create_payment_intent, name='payment-create-intent'),
    path('payments/confirm/', views.confirm_payment, name='payment-confirm'),

    path('osimart/banners/', views_osimart.osimart_banners, name='osimart-banners'),
    path('osimart/banners/<str:banner_id>/', views_osimart.osimart_banner_detail, name='osimart-banner-detail'),
    path('osimart/products/', views_osimart.osimart_products, name='osimart-products'),
    path('osimart/products/<str:product_id>/', views_osimart.osimart_product_detail, name='osimart-product-detail'),
    path('osimart/categories/', views_osimart.osimart_categories, name='osimart-categories'),
    path('osimart/categories/<str:category_id>/', views_osimart.osimart_category_detail, name='osimart-category-detail'),
    path('osimart/store/', views_osimart.osimart_store, name='osimart-store'),
    path('osimart/home/', views_osimart.osimart_home, name='osimart-home'),
    path('osimart/brands/', views_osimart.osimart_brands, name='osimart-brands'),
    path('osimart/brands/<str:brand_id>/', views_osimart.osimart_brand_detail, name='osimart-brand-detail'),
    path('osimart/collections/', views_osimart.osimart_collections, name='osimart-collections'),
    path('osimart/collections/<str:collection_id>/', views_osimart.osimart_collection_detail, name='osimart-collection-detail'),
    path('osimart/quantity-units/', views_osimart.osimart_quantity_units, name='osimart-quantity-units'),
    path('osimart/variant-types/', views_osimart.osimart_variant_types, name='osimart-variant-types'),
    path('osimart/variant-types/<str:vt_id>/', views_osimart.osimart_variant_type_detail, name='osimart-variant-type-detail'),
    path('osimart/announcement-bars/', views_osimart.osimart_announcement_bars, name='osimart-announcement-bars'),
    path('osimart/announcement-bars/<str:ann_id>/', views_osimart.osimart_announcement_bar_detail, name='osimart-announcement-bar-detail'),
    path('osimart/customers/', views_osimart.osimart_customers, name='osimart-customers'),
    path('osimart/customers/<uuid:customer_id>/', views_osimart.osimart_customer_detail, name='osimart-customer-detail'),
    path('osimart/medias/', views_osimart.osimart_medias, name='osimart-medias'),
    path('osimart/medias/<uuid:media_id>/', views_osimart.osimart_media_detail, name='osimart-media-detail'),
    path('osimart/shipping-zones/', views_osimart.osimart_shipping_zones, name='osimart-shipping-zones'),
    path('osimart/shipping-zones/<str:zone_id>/', views_osimart.osimart_shipping_zone_detail, name='osimart-shipping-zone-detail'),
    path('osimart/order-status-choices/', views_osimart.osimart_order_status_choices, name='osimart-order-status-choices'),
    path('osimart/order-status-choices/<str:status_id>/', views_osimart.osimart_order_status_choice_detail, name='osimart-order-status-choice-detail'),
    path('osimart/cart/view/', views_osimart.osimart_cart_view, name='osimart-cart-view'),
    path('osimart/cart/update-item/', views_osimart.osimart_cart_update_item, name='osimart-cart-update-item'),
]
